name: socha
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48067
title: 'FRESH & WILD'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#d5d1cd'
    - '#acabb0'
    - '#323433'
    - '#6b615c'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.21422428637742996
purpose: []
